# Generated by Django 4.2.5 on 2023-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default='1111-11-11 11:11:11'),
        ),
        migrations.AddField(
            model_name='order',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
